name: ./just build
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/just-build.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/just-build.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  just-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add wasm32-wasi
      - run: rustup target add wasm32-wasi-preview1-threads
      - run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: ./just build
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: pkg
